# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# .github/workflows/example-1.yml

name: Manual Run
on: [workflow_dispatch]
jobs:
  example:
    name: Spinning the Env
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name:  Install Google Chrome # Using shell script to install Google Chrome
        run:   |
            chmod +x ./scripts/chromeinstaller.sh
                    ./scripts/chromeinstaller.sh 
      - name:  Install Firefox # Using shell script to install Google Chrome
        run:   |
          chmod +x ./scripts/InstallFirefox.sh
                    ./scripts/InstallFirefox.sh 
      - name: Build with Maven
        run: mvn test --file pom.xml
